databases:
  - name: lm-seamless
    databaseName: lm-seamless
    user: lm-seamless
    plan: free

services:
  - type: web
    name: lm-seamless
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lm-seamless
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false